### ISSUE TITLE
People page

### ISSUE THREAD

**Issue by amalnanavati** [v1shanker/TeknowledgeWebsite#20] opened 2017-09-12 22:31 UTC
We should add a people page, which will include: 1) current Teknow team members and mentors, 2) Teknow alumni, and 3) (optional) CMU and community members that have been instrumental in supporting our program (including Mark, Kosbie, Aileen, Michael Chapman, James Brown, etc.)

**Comment by elpintar** [comment] 2017-09-21 20:15
Duplicate of #12

**Closed as completed** 2017-09-21 20:15 UTC
